- name: configuring trunk interface on {{ inventory_hostname }}
  cisco.ios.ios_config:
    lines:
    - switchport trunk allowed vlan add {{hostvars['localhost']['access_vlan']}}
    - switchport trunk encapsulation dot1q
    - switchport mode trunk
    parents: interface {{ trunk_port }}

- name: Save the switch running config on {{ inventory_hostname }}
  ios_config:
    save_when: always