---
all:
  children:
    pod1:
      children:
        routers:
          hosts:
            pod1r1:   
        core_switches:
          hosts:
            pod1sw1:
            pod1sw2:
        access_switches:
          hosts:
            pod1sw3:                   
          
              
